dist: trusty
sudo: false

jobs:
  include:
    - name: Python 3.7 on Ubuntu Linux 18.04
      os: linux
      dist: bionic
      language: python
      python: '3.7'
    - name: Python 3.8 on Ubuntu Linux 18.04
      os: linux
      dist: bionic
      language: python
      python: '3.8'
    # See https://blog.travis-ci.com/2019-08-07-extensive-python-testing-on-travis-ci
    # for macos config peculiarities.
    - name: Python 3.7 on MacOS X (xcode 10.3)
      os: osx
      language: shell
      osx_image: xcode10.3  # Python 3.7
    - name: Python 3.7 on MacOS X (xcode 11.3)
      os: osx
      language: shell
      osx_image: xcode11.3  # Python 3.7.5
      

cache:
  directories:
  - $HOME/.cache/pip

install:
  # install miniconda
  - deactivate
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - MINICONDA_PATH=/home/travis/miniconda
  - chmod +x miniconda.sh && ./miniconda.sh -b -p $MINICONDA_PATH
  - export PATH=$MINICONDA_PATH/bin:$PATH
  - conda update --yes conda
  # create the testing environment
  - conda create -n testenv --yes python=$PYTHON_VERSION pip
  - source activate testenv
  - |
      if [ $SKLEARN_VERSION = "nightly" ]; then
          conda install --yes numpy==$NUMPY_VERSION scipy==$SCIPY_VERSION cython nose r rpy2 numba matplotlib pytest pytest-cov
          # install nightly wheels
          pip install --pre -f https://sklearn-nightly.scdn8.secure.raxcdn.com scikit-learn
      else
          conda install --yes numpy==$NUMPY_VERSION scipy==$SCIPY_VERSION scikit-learn==$SKLEARN_VERSION cython nose r rpy2 numba matplotlib pytest pytest-cov
      fi
  - pip install codecov
  - pip install .

script:
  - pytest -v --cov=skdim --pyargs skdim

after_success:
  - codecov
